### ISSUE TITLE
Stickers wear

### ISSUE THREAD

**Issue by dennissimmo** [csgofloat/CSGOFloat-Extension#93] opened 2020-09-19 15:00 UTC
Hi, can you add parathemer "wear" for sticker , when returning json from inpect url by example "https://api.csgofloat.com/?url=steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198984091613A19282557712D11880652775751478859"
Simple add another field named wear, which will return value [0,100] or it is unreal?
Thank you!

**Comment by Step7750** [comment] 2020-09-19 23:27
Duplicate of https://github.com/csgofloat/CSGOFloat-Inspect/issues/79

**Closed by Step7750** 2020-09-19 23:27 UTC
